### ISSUE TITLE
word2vec을 구현할 때 u, v 벡터를 구분해서 만드는 이유

### ISSUE THREAD

**Issue by jeongukjae** [jeongukjae/CS224n-study#3]

**Comment by seo-jinBro** [comment]
u,v 벡터를 구분한다는게 어떤 말씀이신지 부연해주실수있나용?

**Comment by jeongukjae** [comment]
하나의 단어에 대해서 context word일 때 벡터 하나와 center word일때 벡터 하나를 구분해서 쓰더라고요!

**Comment by jeongukjae** [comment]
이것도 2강 다시 듣다보니까 나오네요 ㅠㅠ easier optimization이 그 이유라고 하고, 끝나고 둘의 평균을 취한다고 합니다. 단어 하나당 하나의 벡터만을 이용해서 구현이 가능하다고 하네요

**Comment by Baekyeongmin** [comment]
이거에 대해서는 처음에 저도 좀 어려웠는데, word2vec 논문 보니까 잘 이해된 것 같아요! 보통 잘 학습이되면 u,v가 representation value 자체는 차이가 있겠지만 test시에(syntectic, symentic) vector연산을 수행하여 (dot product) 유사도를 구할 때에는 크게 차이가 없다고 합니다. 그래서 학습이 잘 되면 u,v 중 어떤 걸 사용해도 상관없으나 둘 다 사용한 경우 정확도가 조금 오르기 때문에 word2vec, glove 논문에서는 그렇게 했다고 나와있네요!
